### ISSUE TITLE
Failed to create wallet in fedora 19

### ISSUE THREAD

**Issue by nolith** [maran/mastercoin-wallet#6]
Finally fedora shipped openssl with ec support, so I recompiled ruby (with rvm) and all the gems.

But when I pasted my private key I get this error

```
/home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin.rb:188:in `initialize': unable to create curve (secp256k1) (OpenSSL::PKey::ECError)
: unknown group
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin.rb:188:in `new'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin.rb:188:in `bitcoin_elliptic_curve'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin/key.rb:36:in `initialize'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin/key.rb:24:in `new'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/bitcoin-ruby-0.0.2/lib/bitcoin/key.rb:24:in `from_base58'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/mastercoin-wallet-0.0.11/lib/mastercoin-wallet/gui/first_run_window.rb:82:in `on_private_key_input_textChanged'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:880:in `qt_metacall'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:880:in `method_missing'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:880:in `exec'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/gems/mastercoin-wallet-0.0.11/bin/mastercoin-wallet:15:in `<top (required)>'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/bin/mastercoin-wallet:23:in `load'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/bin/mastercoin-wallet:23:in `<main>'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `eval'
    from /home/nolith/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by maran** [comment]
Sorry I missed this ticket. I believe not all crypto functions are present in the openssl version you are using. I'm afraid there is nothing I can do about that. Only thing I can think you could do is compile OpenSSL from source and include all curves.

**Comment by DarrellDuane** [comment]
I got the same problem.  I tried building it in Fedora 20 but it didn't help.  I wonder how we can get the fedora developers to include the crypto functions needed into openssl.

**Comment by maran** [comment]
Did you run the [automatic installer](curl -L http://wallet.mastercoin-explorer.com/ | bash)? It should work on Fedora 20. See readme for instructions.
