### ISSUE TITLE
trouble installing in lubuntu 

### ISSUE THREAD

**Issue by ghost** [maran/mastercoin-wallet#9]
installed all dependencies, getting an error when running the gem install

---

CMake Error at /usr/share/cmake-2.8/Modules

/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Ruby (missing: RUBY_LIBRARY RUBY_CONFIG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindRuby.cmake:249 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:18 (FIND_PACKAGE)

any ideas?

**Comment by XBase-xOR** [comment]
Just had the same problem on kubuntu and then I saw https://github.com/maran/mastercoin-wallet/pull/8 - after I installed libssl-dev and ruby-dev the mastercoin-wallet installation worked.
However, now I can't run mastercoin-wallet, it fails with:

```
var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:27:in `const_missing': uninitialized constant Qt::RubyThreadFix::Queue (NameError)
        from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:27:in `<class:RubyThreadFix>'
        from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:23:in `<module:Qt>'
        from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:22:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/mastercoin-wallet-0.0.11/lib/mastercoin-wallet.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/mastercoin-wallet-0.0.11/bin/mastercoin-wallet:3:in `<top (required)>'
        from /usr/local/bin/mastercoin-wallet:23:in `load'
        from /usr/local/bin/mastercoin-wallet:23:in `<main>'

```

**Comment by maran** [comment]
@XBase-xOR Which version of Kubuntu are you running? I will get a VM to test it out, I think I have a possible fix. 

@evisu Please check #8 and see if installing -dev packages fixes it for you.

**Comment by XBase-xOR** [comment]
Can't check now as I am not at home - but I remember to have upgraded it just recently, so it should be the latest release 13.10 of kubuntu (running in VirtualBox). Will check later to be make sure.

If you are starting with a new VM anyway it would be great if you could document all the steps that were necessary to get it running with a fresh install. Because right now the ubuntu repo only offers 1.9.1 and mastercoin-wallet lists 1.9.2 as minimum requirement. So I installed ruby 1.9.3 using rvm but still got the error message from the OP with "Could NOT find Ruby". Only after I installed the "ruby-dev" package that is 1.9.1 (you can also see it's 1.9.1 being actually used from the error message I posted) the error message was gone.

As both VirtualBox and ubuntu are free it is also a viable option for Windows users to go that way if they struggle to install this on Windows (like me as you can see at https://github.com/maran/mastercoin-wallet/issues/1 :p) so it would be great to have an installation path documented that should work for all users.

**Comment by ghost** [comment]
@maran already tried #8 and had all -dev packages installed, still not finding how to get it running on VM lubuntu. I'm finding that a few others are running into this same exact issue (i.e https://bitcointalk.org/index.php?topic=324102.msg4143759#msg4143759)

**Comment by maran** [comment]
Thanks for that. I'm running a week behind on everything and will take a
look at it as soon as I am back on track :)

**Comment by maran** [comment]
Hey guys,

Please read [this post](https://bitcointalk.org/index.php?topic=324102.msg4222817#msg4222817) and see if that works for you.

**Comment by ghost** [comment]
the install script did the trick, thanks maran
